; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.22"

; Modules
projects[admin_menu][version] = "3.0-rc4"

projects[ctools][version] = "1.3"

projects[devel][version] = "1.3"

projects[diff][version] = "3.2"

projects[entity][version] = "1.0"

projects[features][version] = "2.0-beta2"

projects[libraries][version] = "2.1"

projects[rules][version] = "2.3"

projects[token][version] = "1.5"

projects[views][version] = "3.6"

